#!/bin/bash

# Set Gpyro version number, compiler suffix, and whether or not to use debug executables
GPYRO_VER=0.8200

# This script uses several environment variables to specify locations of Gpyro 
# and MPI executables. Since the values specified in lines 18-32 below are probably
# not appropriate for your system, you will have to add lines similar to the 
# following to your ~/.bashrc file:
#
# export GPYRO_BINARY_DIRECTORY=/usr/local/bin
# export GPYRO_MPIRUN=/usr/local/openmpi-1.10.3_gnu/bin/mpirun
# export GPYRO_COMPILER=gnu # Set to 'gnu' or 'intel'
# export GPYRO_DEBUG=no # Set to 'yes' or 'no'
   
# Set GPYRO_BINARY_DIRECTORY to directory containing gpyro binaries. Note
# that this environment variable is also set in make_intel.sh and make_gnu.sh.
if [ -z "$GPYRO_BINARY_DIRECTORY" ]; then
   GPYRO_BINARY_DIRECTORY=/usr/local/bin
fi

# Set GPYRO_MPIRUN to full path to mpirun for MPI installation. 
# (edit the file 'machines.linux' to specify host names)
if [ -z "$GPYRO_MPIRUN" ]; then
   GPYRO_MPIRUN=/usr/local/openmpi-2.1.0_${GPYRO_COMPILER}/bin/mpirun
fi

# Set GPYRO_COMPILER to either 'gnu' or 'intel' as these suffices are appended
# to the binary files generated by the build scripts
if [ -z "$GPYRO_COMPILER" ]; then
   GPYRO_COMPILER=gnu
fi

# Set GPYRO_DEBUG to either 'yes' or 'no' depending on whether or not you want 
# to run the 
if [ -z "$GPYRO_DEBUG" ]; then
   GPYRO_DEBUG=no
fi

rm -f ./gpyro
rm -f ./gpyro_propest
rm -f ./fds6_gpyro

if [ $GPYRO_DEBUG = "yes" ]; then
   ln -s $GPYRO_BINARY_DIRECTORY/gpyro_${GPYRO_VER}_debug_${GPYRO_COMPILER} gpyro
   ln -s $GPYRO_BINARY_DIRECTORY/gpyro_propest_${GPYRO_VER}_debug_${GPYRO_COMPILER} gpyro_propest
   ln -s $GPYRO_BINARY_DIRECTORY/fds6_mpi_22343_gpyro_${GPYRO_VER}_debug_${GPYRO_COMPILER} fds6_gpyro
else
   ln -s $GPYRO_BINARY_DIRECTORY/gpyro_${GPYRO_VER}_${GPYRO_COMPILER} gpyro
   ln -s $GPYRO_BINARY_DIRECTORY/gpyro_propest_${GPYRO_VER}_${GPYRO_COMPILER} gpyro_propest
   ln -s $GPYRO_BINARY_DIRECTORY/fds6_mpi_22343_gpyro_${GPYRO_VER}_${GPYRO_COMPILER} fds6_gpyro
fi

echo "Sample 01"
cd 01-dtg
../gpyro ./sample_01.data > log.txt
cd ..

echo "Sample 02"
cd 02-thermoplastic
../gpyro ./sample_02.data > log.txt
cd ..

echo "Sample 03"
cd 03-char
../gpyro ./sample_03.data > log.txt
cd ..

echo "Sample 04"
cd 04-intumescent
../gpyro ./sample_04.data > log.txt
cd ..

echo "Sample 05"
cd 05-smolder
../gpyro ./sample_05.data > log.txt
cd ..

echo "Sample 06"
cd 06-oxidative_pyrolysis
../gpyro ./sample_06.data > log.txt
cd ..

echo "Sample 07"
cd 07-2d
../gpyro ./sample_07.data > log.txt
cd ..

echo "Sample 08"
cd 08-3d
../gpyro ./sample_08.data > log.txt
cd ..

# Uncomment the "exit 0" to prevent the MPI samples from running:
#exit 0

echo "Sample 09"
cd 09-dtg_ga
$GPYRO_MPIRUN -np 9 -machinefile ./machines.linux ../gpyro_propest > log.txt
cd ..

echo "Sample 10"
cd 10-char_ga
$GPYRO_MPIRUN -np 17 -machinefile ./machines.linux ../gpyro_propest > log.txt
cd ..

echo "Sample 11"
cd 11-fds6_gpyro_coupled
$GPYRO_MPIRUN -np 16 -machinefile ./machines.linux ../fds6_gpyro crib.fds > log.txt
cd ..

exit 0
